### PR TITLE
Feature/label project

### PR DESCRIPTION
**Pull request by abdirahmanfarah**
# Description
Linked Columns to Programs, and updated schema to only take whether a product or a project is in active state rather than the three different ways we were tracking before. Both Columns and Labels can be created, deleted and updated. To create a label, you need a column id. To create a column you need a program id. 

Fixes # (issue)
-Can seed now. No more errors.

## Type of change
Schema update.
Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Change Status

- [x] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

# How Has This Been Tested?

- [x] Test A
- [x] Test B

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] There are no merge conflicts

### CODE REVIEW

**Comment by lawsonarichard** [comment]
Pulled down and using the current master front end to test. Getting 400 bad request...probably due to some changes that aren't reflected, seed of the data or the query on the front end. 

Is there a corresponding front end branch?

**Comment by abdirahmanfarah** [comment]
> Pulled down and using the current master front end to test. Getting 400 bad request...probably due to some changes that aren't reflected, seed of the data or the query on the front end.
> 
> Is there a corresponding front end branch?

**Comment by abdirahmanfarah** [comment]
> Pulled down and using the current master front end to test. Getting 400 bad request...probably due to some changes that aren't reflected, seed of the data or the query on the front end.
> 
> Is there a corresponding front end branch?

Yes, working on the front-end to reflect the changes right now. Mainly changing status to productActive or projectActive.

**Comment by BryanKAdams** [comment]
Looks like using this with the corresponding front end branch everything works fine, is the front end branch still being worked on to incorporate these changes? Good work guys.

**Comment by abdirahmanfarah** [comment]
> Pulled down, tested with corresponding front end. Since this function is not usable on front end due to front ends current state, I've ran a few tests through the Apollo (:8000) and Prisma (:7000) playground.
> 
> `mutation { createColumn( data: {name:"Status 1", program: { create: {name: "Labs 22"}}}){ name id } }`
> While running this mutation on :7000 I get the proper response
> 
> `{ "data": { "createColumn": { "name": "Status 1", "id": "ck7gh6r8x1ana0732s488qo66" } } }`
> And can query the column!
> 
> But on Apollo :8000 I am receiving
> 
> ` "error": { "errors": [ { "message": "Unknown argument \"data\" on field \"createColumn\" of type \"Mutation\".", "locations": [ { "line": 2, "column": 16 } ], "extensions": { "code": "GRAPHQL_VALIDATION_FAILED"`

You don't need to add data on the Apollo Server. Just pass the parameters of which in this case is name and id like this: 

mutation{
 createColumn(name: "Status 1" id:"ck7fd63hz00700876n6zpisig" ){
  name
  id
  
}
}

**Pull request merged**
